site_name: NWSL Data
site_url: https://nwsldata.com/research
docs_dir: docs
site_dir: ../public/research
site_description: Advanced data analysis and predictive modeling for the National Women's Soccer League

theme:
  name: material
  font:
    text: false  # Disable default font loading
    code: Roboto Mono
  palette:
    # Light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode  
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy

nav:
  - Home: index.md
  - Over/Under 2.5 Goals Prediction: over-under-goals-prediction.md
  - Test Research: test-research.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - tables

plugins:
  - search

extra:
  homepage: https://nwsldata.com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tom-mcmillan/nwsl-nextjs-web

extra_css:
  - stylesheets/extra.css